### ISSUE TITLE
怎么开启redis呢？

### ISSUE THREAD

**Issue by mutuyihao** [HalcyonAzure/lsky-pro-docker#14]
图床已经用docker的方式安装好了，是否再单独安装个redis（不限docker），然后去修改env，连接上就可以了

**Comment by HalcyonAzure** [comment]
刚刚才看见这个issues抱歉，只需要在dockerfile的install-php里面添加一个php-redis就可以了，这个我之前在本地测试完后忘记提交到github上了，稍后会更新加上，如果还有需求的话可以测试看看

**Comment by mutuyihao** [comment]
好的，感谢。我之前也想过这样做，把你的dockerfile下载到vps上，然后docker build，不知道为啥没安装上lsky程序。你这样更新完，docker hub里的镜像也直接是更新的了吧，那我可以直接docker pull新镜像吧。

**Comment by mutuyihao** [comment]
> 刚刚才看见这个issues抱歉，只需要在dockerfile的install-php里面添加一个redis就可以了，这个我之前在本地测试完后忘记提交到github上了，稍后会更新加上，如果还有需求的话可以测试看看

好的，感谢。我之前也想过这样做，把你的dockerfile下载到vps上，然后docker build，不知道为啥没安装上lsky程序。你这样更新完，docker hub里的镜像也直接是更新的了吧，那我可以直接docker pull新镜像吧。

**Comment by HalcyonAzure** [comment]
Latest的tag还没有更新上，你可以用halcyonazure/lsky-pro-docker:dev这个tag测试看看，latest的话今天晚一点应该就会自动更新了

**Comment by mutuyihao** [comment]
> Latest的tag还没有更新上，你可以用halcyonazure/lsky-pro-docker:dev这个tag测试看看，latest的话今天晚一点应该就会自动更新了

感谢大佬，嗯拉了dev的。用docker 装了redis，在docker 容器间通信折腾了一会。查看redis cli 已经有缓存命中了。再次感谢！！！

**Comment by HalcyonAzure** [comment]
解决了就好🤣
