### ISSUE TITLE
我是用docker-compose部署了，页面响应速度非常慢

### ISSUE THREAD

**Issue by yayaQAQ** [HalcyonAzure/lsky-pro-docker#15]
不知道是这个软件自身响应速度慢，还是windows docker的原因，不过我之前部署的其他服务的速度并没有慢。
不知道作者或者其他人有遇到过相同的问题没有。

**Comment by yayaQAQ** [comment]
点击一个按钮，大约需要5s以上才会返回请求，更新页面

**Comment by HalcyonAzure** [comment]
也许可以打开浏览器的F12->右上角的`Network`，然后通过`ctrl+f5`刷新请求，看看是哪一部分消耗的时间比较长，我个人没有遇到过这个问题:confused:

**Comment by Karlvision** [comment]
我的延迟2S，
![image](https://github.com/HalcyonAzure/lsky-pro-docker/assets/50682981/b3c084e7-6254-40e7-9319-707ce6db2454)
这个怎么解决呢

**Comment by HalcyonAzure** [comment]
> 我的延迟2S， ![image](https://user-images.githubusercontent.com/50682981/258983698-b3c084e7-6254-40e7-9319-707ce6db2454.png) 这个怎么解决呢

在我这里同样的请求时间要少一个数量级，是不是网络问题？
![请求image](https://github.com/HalcyonAzure/lsky-pro-docker/assets/53591299/36a2d8b3-4f8a-4066-8f9a-34bf60170678)
