### ISSUE TITLE
wsl没有公网ip

### ISSUE THREAD

**Issue by xq182** [HalcyonAzure/lsky-pro-docker#16]
如果用部署在wsl上，图片的url好像就不能配自己的域名了

**Comment by HalcyonAzure** [comment]
在WSL中使用自己的域名是什么意思？有用`Nginx`转发`Docker`的服务出来吗？还是说你的问题是在没有公网IP的情况下怎么部署让外网可以访问的图床服务器？

**Comment by xq182** [comment]
嗯，没有公网IP的情况下部署不了自己的域名

**Comment by xq182** [comment]
嗯，没有公网IP的情况下部署不了外网访问的域名

**Comment by HalcyonAzure** [comment]
那可以谷歌搜索”内网穿透“，看看相关的教程。这个不属于仓库镜像本身的问题了。如果后续在部署镜像的时候发现镜像缺少依赖等问题可以再反馈。
