### ISSUE TITLE
小白所不会解决的问题，求解大神

### ISSUE THREAD

**Issue by cabcenturywave** [HalcyonAzure/lsky-pro-docker#2]
本人纯小白，想请教大神发生这种情况，应该如何操作修改？
跪求大神解答谢谢！
日志里的报错：
2022/3/31 13:42:05  AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using fd00:db7::242:ac11:d. Set the 'ServerName' directive globally to suppress this message
使用时候的问题：
![image.png](https://s2.loli.net/2022/03/31/xDG3mOZ1iJzEjop.png)

**Comment by HalcyonAzure** [comment]
> 本人纯小白，想请教大神发生这种情况，应该如何操作修改？ 跪求大神解答谢谢！ 日志里的报错： 2022/3/31 13:42:05 AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using fd00:db7::242:ac11:d. Set the 'ServerName' directive globally to suppress this message 使用时候的问题： ![image.png](https://camo.githubusercontent.com/30aa391756c79be4260506f36583db9173bb8a0d7382c398e359a0df16eeaa15/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30332f33312f784447336d4f5a31694a7a456a6f702e706e67)

图裂了，不太清楚你遇到的具体情况

**Comment by cabcenturywave** [comment]
这是网页端显示的
https://s1.ax1x.com/2022/04/02/qTSVaD.png
这是日志中显示的
https://s1.ax1x.com/2022/04/02/qTSkqK.png

**Comment by cabcenturywave** [comment]
> 

这是网页端显示的
https://s1.ax1x.com/2022/04/02/qTSVaD.png
这是日志中显示的
https://s1.ax1x.com/2022/04/02/qTSkqK.png

**Comment by cabcenturywave** [comment]
> > 本人纯小白，想请教大神发生这种情况，应该如何操作修改？ 跪求大神解答谢谢！ 日志里的报错： 2022/3/31 13:42:05 AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using fd00:db7::242:ac11:d. Set the 'ServerName' directive globally to suppress this message 使用时候的问题： ![image.png](https://camo.githubusercontent.com/30aa391756c79be4260506f36583db9173bb8a0d7382c398e359a0df16eeaa15/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30332f33312f784447336d4f5a31694a7a456a6f702e706e67)
> 
> 图裂了，不太清楚你遇到的具体情况

大神您好，现在情况是这样的
这是上传图片失败的情况截图
[![qTSVaD.png](https://s1.ax1x.com/2022/04/02/qTSVaD.png)](https://imgtu.com/i/qTSVaD)
这是日志的截图
[![qTSkqK.png](https://s1.ax1x.com/2022/04/02/qTSkqK.png)](https://imgtu.com/i/qTSkqK)

**Comment by HalcyonAzure** [comment]
有用Nginx反代吗？这个日志能看到的内容也比较有限，建议下载完整日志提问。不过目前感觉可能问题出在Docker或Nginx没有正确配置
