### ISSUE TITLE
容器化部署升级软件版本时要保留和删除哪些目录

### ISSUE THREAD

**Issue by kanon-H** [HalcyonAzure/lsky-pro-docker#20]
您好，现在遇到一个问题，从2.0版本部署的兰空图床，现在想要升级到2.1要如何操作，直接docker-compose 更换镜像版本，无法覆盖容器工作目录（数据卷）下的代码，如果删除某些目录再升级又会造成图片丢失，因为这个容器数据卷映射的是整个工作目录，所以想请教下升级软件版本要如何操作

**Comment by HalcyonAzure** [comment]
应该可以在系统设置的最下面直接手动更新到最新版，不需要替换其他文件。你在控制面板找找看？

**Comment by kanon-H** [comment]
额，容器部署手动更新好像不行，不知道为啥，我再研究研究看看其他方式迁移，感谢

**Comment by HalcyonAzure** [comment]
根据`Lsky-Pro`的官方文档手动升级即可：[升级｜Lsky Pro](https://docs.lsky.pro/docs/free/v2/quick-start/upgrade.html)
