### ISSUE TITLE
dockerhub中的端口好像写错了

### ISSUE THREAD

**Issue by boxknight** [HalcyonAzure/lsky-pro-docker#23]
github项目中写的容器内部管理端口是8089
可是在[dockerhub](https://hub.docker.com/r/halcyonazure/lsky-pro-docker)里写的管理端口是80
我前几天部署的时候用-p 9080:80时是不管用的，我追到github里才发现是-p 8089:8089 应该是dockerhub里写错了

**Comment by HalcyonAzure** [comment]
噢噢确实，前几天更新了环境变量控制端口以后Docker Hub那边Readme忘记更新了，我改改，多谢提醒！

**Comment by HalcyonAzure** [comment]
改好了！

**Comment by boxknight** [comment]
OwO 好快！

**Comment by HalcyonAzure** [comment]
刚好在线XD

**Comment by backunderstar** [comment]
呜呜，搞了一晚上，都出不来页面，到这看才知道咋回事
