### ISSUE TITLE
docker-compose部署如何迁移

### ISSUE THREAD

**Issue by backunderstar** [HalcyonAzure/lsky-pro-docker#24]
开发者您好，我想问下，如果想更换服务器（反代后域名不变），该怎样迁移数据。
希望可以得到指正：
* $PWD/mysql/data文件打包迁移到另一个服务器相同位置，再进行docker-compose部署，最后反代。

请问这样有可行性吗，或者是否有疏漏？
因数据较多原因，还未进行迁移，想得到更专业点的想法
非常感谢

**Comment by HalcyonAzure** [comment]
以我个人的情况来说，按照README的文档我的文件目录结构大致如下：
```shell
> tree lsky-pro -L 2
lsky-pro
|-- docker-compose.yaml
|-- lsky
|   `-- web
`-- mysql
    |-- conf
    |-- data
    `-- log
```
在迁移的时候最无脑的方式就是直接将最上层的lsky-pro文件夹（就是包含了`docker-compose.yaml`、`lsky`和`mysql`的文件夹）整个进行打包，由于$PWD是指相对目录，因此在另外一台机器上不需要担心路径映射的问题，直接解压了lsky-pro以后进行`docker-compose up -d`应该就可以了。

**Comment by backunderstar** [comment]
好的，谢谢说明
