### ISSUE TITLE
curl error 6: getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by kuangmeng** [HalcyonAzure/lsky-pro-docker#28]
这个问题有遇到嘛？

**Comment by HalcyonAzure** [comment]
想问一下这个报错是出现在了哪个位置？

**Comment by kuangmeng** [comment]
我给原来的代码增加了oauth登录。在本地测试没问题，然后我打包到docker，在我的NAS上运行，就出现这个错误。应该是curl 不通我的认证器的授权链接。这个问题你有遇到过嘛？

**Comment by HalcyonAzure** [comment]
我自己也是docker跑在自己的NAS上运行，没遇到这个问题，试了下手动`curl`请求`cloudflare.com`也可以正常请求，有什么办法可以复现你这个问题吗？

**Comment by kuangmeng** [comment]
可能是我内网的原因？

**Comment by HalcyonAzure** [comment]
有可能，也许是宿主机配置了网络代理，但是`Docker`容器内没有配置网络代理一类的问题？ :eyes:

**Comment by lenvonsam** [comment]
我这边也有同样的问题，请问这个问题解决了吗
