### ISSUE TITLE
重新部署配置无法保留

### ISSUE THREAD

**Issue by zheyiyuezhuo** [HalcyonAzure/lsky-pro-docker#3]
如题，只映射`/var/www/html/storage`目录，在容器更改了配置（或者版本更新后）无法保存配置，需要重新配置数据库和管理员等，且配置完进去可能和之前的有冲突，会导致错误500，无法正常使用，不知道我是特例还是都是这样的。

目前尝试映射：`/var/www/html/config`、`/var/www/html/app`、`/var/www/html/.env`都没办法保存配置数据，只能映射整个`/var/www/html`目录到本地，这样删除容器重新部署不会丢失配置数据，但是不知道对后续升级有什么影响。

不知道可不可以优化下结构，把各种配置文件修改到某一个目录，这样方便docker升级重新部署等操作！（之前截的图忘保存了，提交issues时候才发现没有图尴尬）

**Comment by HalcyonAzure** [comment]
storage无法保留的问题我在当时写了这个仓库的文档后调试到时候发现了，然后在lsky-pro那边的issue下面修改文档删除并修改为了映射全目录，但在这里忘记改了，晚些的时候我把这个仓库对应的文档也修改一下，感谢提出。

anyway，因为lsky-pro的更新和配置在第一次部署完之后，可以在webui的管理界面直接后台更新，不需要以重新部署镜像的方式进行手动更新。理论上对后续也没有额外影响，因此就没有研究目录结构优化问题了。
