### ISSUE TITLE
该镜像是不是不支持arm架构的机子

### ISSUE THREAD

**Issue by xyzbz** [HalcyonAzure/lsky-pro-docker#32]

**Comment by HalcyonAzure** [comment]
是的，目前没有做ARM的支持，因为我自己没有ARM设备。不过最近假期也许会尝试做个适配

**Comment by HalcyonAzure** [comment]
很抱歉现在才完成`arm64`相关的适配，本身其实只需要在`github actions`构建那边加一个平台就行。如果您还有需要的话在今天晚点时候支持`arm64`的镜像就会构建完毕，如果已经使用了其他方法部署也祝您图床运行顺利XD

**Comment by xyzbz** [comment]
好的，晚点测试一下，主要是nas是ARM架构的。
