### ISSUE TITLE
图片管理中部分缩略图加载异常

### ISSUE THREAD

**Issue by cj919837775** [HalcyonAzure/lsky-pro-docker#33]
图片管理中部分缩略图加载异常，不是固定的缩略图加载异常 是随机性的 但是点击进去又是显示正常 麻烦大佬看下是不是apache性能太低跟不上 盼切大佬修复~

![image](https://github.com/HalcyonAzure/lsky-pro-docker/assets/42278054/a87084f4-0f86-49a8-b871-130faa654ea2)
![image](https://github.com/HalcyonAzure/lsky-pro-docker/assets/42278054/f3da61f4-eedc-4511-9adc-89a5b8e74e3b)

**Comment by HalcyonAzure** [comment]
浏览器F12有控制台那边的报错吗？图床是通过反向代理访问会出现这个问题还是说直连就会出现这个问题？图床目前已经存储的图片数量大概在一个什么数量级？🧐

**Comment by cj919837775** [comment]
反向代理     不到三十张的量级
![image](https://github.com/HalcyonAzure/lsky-pro-docker/assets/42278054/4049316b-b6a1-4ee4-82a2-4f07f0249361)
数量是不固定的   有时候是只有几张裂图   多刷新几次   可能又加载正常

**Comment by HalcyonAzure** [comment]
不使用反向代理直连也会出现这个问题吗？我自己的图床大概有100+图片的时候没能复现这个问题，不太好排查

**Comment by HalcyonAzure** [comment]
没有后续反馈这个issue我就先关掉了，后面有问题可以再reopen
