### ISSUE TITLE
请问内存占用过大怎么解决

### ISSUE THREAD

**Issue by hausen1012** [HalcyonAzure/lsky-pro-docker#34]
随着时间增加，越来越吃内存，上次快吃了1g，并且限制内存似乎程序就会直接挂掉，求长期稳定占用比较低的内存方法

**Comment by HalcyonAzure** [comment]
我自己这边部署的情况来说似乎不会出现内存泄漏的问题，有可能相关的导致因素吗？问题应该和容器无关，可以尝试去`Lsky-Pro`主仓库那边也发个`issues`问问。

**Comment by hausen1012** [comment]
ok，感谢，我去看看

**Comment by hausen1012** [comment]
您的占用不会增加吗？一般是多少的占用呢？

**Comment by HalcyonAzure** [comment]
这是我运行了两周以后大概是这个数据：
![运行数据](https://github.com/HalcyonAzure/lsky-pro-docker/assets/53591299/e1ac888f-cbb7-4664-b8d7-1397b5ff5409)
图床的数量级大概在50+左右

**Comment by hausen1012** [comment]
噢噢，我也只有几百张，直接900多m了
![661b890fb3525d2640a8d681867873b](https://github.com/HalcyonAzure/lsky-pro-docker/assets/50026605/26ced60b-c32f-48fe-b696-e53ace391855)

**Comment by HalcyonAzure** [comment]
有容器内的内存占比吗？我这边在容器里面跑了一个top大概是这样的：
![btop](https://github.com/HalcyonAzure/lsky-pro-docker/assets/53591299/9e5dd876-8445-4a19-89fa-071dc959e491)

**Comment by hausen1012** [comment]
这个忘记截图了，等下次截图看看

**Comment by HalcyonAzure** [comment]
没有后续反馈这个issue我就先关掉了，后面有问题可以再reopen
