### ISSUE TITLE
群晖中安装失败SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by bill1112004** [HalcyonAzure/lsky-pro-docker#36]
自检均通过，数据库也已配置。安装提示失败
Dropping all tables ............................................... 9ms FAIL
Installation error!

SQLSTATE[HY000] [2002] Connection refused (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')

如下图
![1700486471873](https://github.com/HalcyonAzure/lsky-pro-docker/assets/142874019/1c8b145f-0262-4ba2-9c15-06d659a077a5)

**Comment by HalcyonAzure** [comment]
docker-compose的内容是怎么样的？感觉可能是MySQL没配置好？

**Comment by bill1112004** [comment]
> docker-compose的内容是怎么样的？感觉可能是MySQL没配置好？

群晖里装的MariaDB10和PhpmyAdmin，新建了lsky数据库

**Comment by HalcyonAzure** [comment]
日志链接打开重定向到了这个`issue`，无法打开。有相关文件吗？

**Comment by bill1112004** [comment]
> 日志链接打开重定向到了这个`issue`，无法打开。有相关文件吗？

哪个issue？这个日志我看了半天，也没看到哪里有报错或者issue

**Comment by HalcyonAzure** [comment]
😂 我点开那个链接会回到咱这个`issue`，就是说你这个链接我没法正确打开你本来要发给我的日志
![image](https://github.com/HalcyonAzure/lsky-pro-docker/assets/53591299/5dc43c28-4e29-4e97-9bb2-c4e6e8e9ea3a)

**Comment by bill1112004** [comment]
> 😂 我点开那个链接会回到咱这个`issue`，就是说你这个链接我没法正确打开你本来要发给我的日志 ![image](https://user-images.githubusercontent.com/53591299/284834551-5dc43c28-4e29-4e97-9bb2-c4e6e8e9ea3a.png)

[halcyonazure-lsky-pro-docker-1.csv](https://github.com/HalcyonAzure/lsky-pro-docker/files/13435523/halcyonazure-lsky-pro-docker-1.csv)

**Comment by HalcyonAzure** [comment]
看lsky-pro的日志看不出啥，都挺正常的。你的数据库是用群晖的GUI方式部署的吗？是的话有配置网络或端口设置吗？

**Comment by bill1112004** [comment]
> 群晖的GUI方式

套件中心部署的MariaDB 10和phpMyAdmin

**Comment by HalcyonAzure** [comment]
尝试一下把Lsky连接数据库的IP地址从`127.0.0.1`改成`172.17.0.1`试试？

**Comment by bill1112004** [comment]
> 尝试一下把Lsky连接数据库的IP地址从`127.0.0.1`改成`172.17.0.1`试试？

搞定，感谢！

**Comment by HalcyonAzure** [comment]
产生这个问题的原因是因为`Lsky-Pro`作为一个`docker`容器运行的时候，`127.0.0.1`指向的是`Lsky-Pro`这个容器的IP，而不是群晖本身的IP，而`172.17.0.1`是群晖默认的`Docker`网络的`IP`。如果你希望在`127.0.0.1`连上数据库的话就需要把`MariaDB`容器的网络模式改为`host`，或者就和现在这样通过默认的`Docker`网桥来连接:wink:。（不是很懂也不要紧，跑起来才是最重要的hhh）

**Comment by loracc802** [comment]
127.0.0.1换成docker中数据库容器的名称。最好不要填具体的IP地址，有时候重启IP会变。

**Comment by chuyegzs** [comment]
这个问题挺奇葩

**Comment by iNiL0119** [comment]
> 产生这个问题的原因是因为`Lsky-Pro`作为一个`docker`容器运行的时候，`127.0.0.1`指向的是`Lsky-Pro`这个容器的IP，而不是群晖本身的IP，而`172.17.0.1`是群晖默认的`Docker`网络的`IP`。如果你希望在`127.0.0.1`连上数据库的话就需要把`MariaDB`容器的网络模式改为`host`，或者就和现在这样通过默认的`Docker`网桥来连接:wink:。（不是很懂也不要紧，跑起来才是最重要的hhh）

127.0.0.1 不是主机 ip 吗？docker ip 是172.17.0.1，容器 ip 应该是从 172.17.0.2（第一个安装的容器）、然后是172.17.0.3（第二个容器）...

**Comment by HalcyonAzure** [comment]
> > 产生这个问题的原因是因为`Lsky-Pro`作为一个`docker`容器运行的时候，`127.0.0.1`指向的是`Lsky-Pro`这个容器的IP，而不是群晖本身的IP，而`172.17.0.1`是群晖默认的`Docker`网络的`IP`。如果你希望在`127.0.0.1`连上数据库的话就需要把`MariaDB`容器的网络模式改为`host`，或者就和现在这样通过默认的`Docker`网桥来连接:wink:。（不是很懂也不要紧，跑起来才是最重要的hhh）
> 
> 127.0.0.1 不是主机 ip 吗？docker ip 是172.17.0.1，容器 ip 应该是从 172.17.0.2（第一个安装的容器）、然后是172.17.0.3（第二个容器）...

你的理解没问题，不过我有点没get到你的问题是？

**Comment by iNiL0119** [comment]
> > > 产生这个问题的原因是因为`Lsky-Pro`作为一个`docker`容器运行的时候，`127.0.0.1`指向的是`Lsky-Pro`这个容器的IP，而不是群晖本身的IP，而`172.17.0.1`是群晖默认的`Docker`网络的`IP`。如果你希望在`127.0.0.1`连上数据库的话就需要把`MariaDB`容器的网络模式改为`host`，或者就和现在这样通过默认的`Docker`网桥来连接:wink:。（不是很懂也不要紧，跑起来才是最重要的hhh）
> > 
> > 
> > 127.0.0.1 不是主机 ip 吗？docker ip 是172.17.0.1，容器 ip 应该是从 172.17.0.2（第一个安装的容器）、然后是172.17.0.3（第二个容器）...
> 
> 你的理解没问题，不过我有点没get到你的问题是？

没理解 “127.0.0.1指向的是Lsky-Pro这个容器的IP，而不是群晖本身的IP” 这句

**Comment by HalcyonAzure** [comment]
> 没理解 “127.0.0.1指向的是Lsky-Pro这个容器的IP，而不是群晖本身的IP” 这句

这个问题是提问者用bridge的方式创建的mysql容器和lsky容器。并且在lsky容器里面填写的mysql数据库的ip是127.0.0.1，而不是mysql本身的容器Ip，所以出现了无法链接的情况。解决方法是改成容器的ip即可。

**Comment by iNiL0119** [comment]
> > 没理解 “127.0.0.1指向的是Lsky-Pro这个容器的IP，而不是群晖本身的IP” 这句
> 
> 这个问题是提问者用bridge的方式创建的mysql容器和lsky容器。并且在lsky容器里面填写的mysql数据库的ip是127.0.0.1，而不是mysql本身的容器Ip，所以出现了无法链接的情况。解决方法是改成容器的ip即可。

数据库路径不是改成 172.17.0.1 吗，这个是 docker 网络 ip，mysql 容器 ip 不是 172.17.0.x 吗？现在主要就是三个 ip，127.0.0.1、172.17.0.1、172.17.0.x，再加上通过公网ip:3306 连接到数据库，网络这一块不太懂

**Comment by HalcyonAzure** [comment]
> 数据库路径不是改成 172.17.0.1 吗，这个是 docker 网络 ip，mysql 容器 ip 不是 172.17.0.x 吗？现在主要就是三个 ip，127.0.0.1、172.17.0.1、172.17.0.x，再加上通过公网ip:3306 连接到数据库，网络这一块不太懂

mysql就是数据库，容器的IP确实是随机的，也就是172.17.0.x。如果你是通过compose部署的甚至还会是172.x.0.x。所以docker在compose中提供了一个叫作hostname字段的能力，可以在你创建容器的时候指定这个容器在docker内的内部域名。在我readme的方案中，因为我设置了mysql-lsky作为数据库的Hostname，所以可以拿这个填在数据库的地址那边。3306是mysql的默认端口。

上述是一些基础知识，如果你的问题是对整一套docker的网络架构，这个可以自己找资料研究下。

**Comment by iNiL0119** [comment]
> > 数据库路径不是改成 172.17.0.1 吗，这个是 docker 网络 ip，mysql 容器 ip 不是 172.17.0.x 吗？现在主要就是三个 ip，127.0.0.1、172.17.0.1、172.17.0.x，再加上通过公网ip:3306 连接到数据库，网络这一块不太懂
> 
> mysql就是数据库，容器的IP确实是随机的，也就是172.17.0.x。如果你是通过compose部署的甚至还会是172.x.0.x。所以docker在compose中提供了一个叫作hostname字段的能力，可以在你创建容器的时候指定这个容器在docker内的内部域名。在我readme的方案中，因为我设置了mysql-lsky作为数据库的Hostname，所以可以拿这个填在数据库的地址那边。3306是mysql的默认端口。
> 
> 上述是一些基础知识，如果你的问题是对整一套docker的网络架构，这个可以自己找资料研究下。

还是有点抽象，脑海中想象的是一个个类似集合的东西，lsky 容器要访问 mysql 容器，必须在同一个集合（docker）进行，如果跳出 docker 这个集合（比如使用127.0.0.1）可能有这样那样的限制，因此在配置 lsky 数据库地址的时候填写的是 172.17.0.1，相当于lsky & mysql 当前处于的一个宿主环境，还请指正

**Comment by iNiL0119** [comment]
> > > 数据库路径不是改成 172.17.0.1 吗，这个是 docker 网络 ip，mysql 容器 ip 不是 172.17.0.x 吗？现在主要就是三个 ip，127.0.0.1、172.17.0.1、172.17.0.x，再加上通过公网ip:3306 连接到数据库，网络这一块不太懂
> > 
> > 
> > mysql就是数据库，容器的IP确实是随机的，也就是172.17.0.x。如果你是通过compose部署的甚至还会是172.x.0.x。所以docker在compose中提供了一个叫作hostname字段的能力，可以在你创建容器的时候指定这个容器在docker内的内部域名。在我readme的方案中，因为我设置了mysql-lsky作为数据库的Hostname，所以可以拿这个填在数据库的地址那边。3306是mysql的默认端口。
> > 上述是一些基础知识，如果你的问题是对整一套docker的网络架构，这个可以自己找资料研究下。
> 
> 还是有点抽象，脑海中想象的是一个个类似集合的东西，lsky 容器要访问 mysql 容器，必须在同一个集合（docker）进行，如果跳出 docker 这个集合（比如使用127.0.0.1）可能有这样那样的限制，因此在配置 lsky 数据库地址的时候填写的是 172.17.0.1，相当于lsky & mysql 当前处于的一个宿主环境，还请指正

类似于家庭网络的概念，同一个网段的设备可以互相通信

**Comment by HalcyonAzure** [comment]
在油管找了个视频，发现B站有搬运，你可以参考看看。如果还有疑问可以通过邮箱或者Telegram私聊咱~ 在issue下讨论这个是比较容易打扰到别人的=-=
https://www.bilibili.com/video/BV1Fk4y1F7Qn

**Comment by LostSheep8** [comment]
> 尝试一下把Lsky连接数据库的IP地址从`127.0.0.1`改成`172.17.0.1`试试？

感谢
