### ISSUE TITLE
Nginx转发Docker容器目前HTTPS的问题是否依旧存在？

### ISSUE THREAD

**Issue by fmuy** [HalcyonAzure/lsky-pro-docker#37]

**Comment by fmuy** [comment]
请问 可以用docker 安装 然后直接用nginx 代理 转静态么

**Comment by HalcyonAzure** [comment]
nginx代理转静态是指？

**Comment by fmuy** [comment]
我不再纠结那个了。我的webdav总是失败。你这个最新的镜像是不是已经修复了https那个相关的设置了

**Comment by HalcyonAzure** [comment]
如果你是在`docker`部署完成以后，可以使用`http://[内网IP]:[端口]`访问的话，目前最新的镜像我自己用`Nginx`直接反向代理对应的`http://[内网IP]:[端口]`到域名（假设是`test.com`）后，是可以直接通过`https://test.com`这样的`https`链接直接访问的。不过因为我不确定具体是否是源码那边修复了，所以`README`里面还一直保留那个解决方案，提供给遇到了问题的用户参考，没遇到问题就最好啦。

>我的webdav总是失败。

指想创建自己的`WebDav`吗？也许可以试试比较火的[alist](https://github.com/alist-org/alist)？

**Comment by fmuy** [comment]
谢谢，问题现在已经解决了
