### ISSUE TITLE
图片信息不能显示真实IP，显示的是宿主机IP

### ISSUE THREAD

**Issue by iqyiqy** [HalcyonAzure/lsky-pro-docker#4]
使用nginx反代后，图片显示显示是宿主机IP。不是用户的真实IP。
请问是我nginx有误吗？看其它地方，据说可能要修改apache的配置。

**Comment by HalcyonAzure** [comment]
> 使用nginx反代后，图片显示显示是宿主机IP。不是用户的真实IP。 请问是我nginx有误吗？看其它地方，据说可能要修改apache的配置。

对于Nginx的详细配置我也不是很清楚，但感觉应该不是容器导致的问题。

**Comment by iqyiqy** [comment]
> 

容器启动后，直接上传图片。IP是显示正常的。加一层nginx代理后，就成了nginx宿主机的IP了。感觉是传递IP出问题了。

**Comment by HalcyonAzure** [comment]
> > 
> 
> 容器启动后，直接上传图片。IP是显示正常的。加一层nginx代理后，就成了nginx宿主机的IP了。感觉是传递IP出问题了。

我大致在Google上搜索关键词“Docker Nginx转发 真实IP”找到了一些相似的例子，但没有深入研究，目前看到的一个比较简单的方案是把Docker容器设置在host网络模式下运行后配置转发也许能解决该问题。我自己目前暂时没有IP检测的需求，不过个人觉得应该是Docker或者Nginx方面的问题，和容器无关。可以先在谷歌或者[百度](https://www.baidu.com/s?ie=UTF-8&wd=Docker%20Nginx%E8%BD%AC%E5%8F%91%20%E7%9C%9F%E5%AE%9EIP)上搜索一些相似情况自己解决。
