### ISSUE TITLE
按照使用Nginx反向代理配置HTTPS进行docker的部署，部署完成后内网访问网页页面加载异常

### ISSUE THREAD

**Issue by 99Mr-Z** [HalcyonAzure/lsky-pro-docker#40]
unraid系统，反代使用的[Nginx Proxy Manager]，目前仅将图床的docker正常部署下来

1.具体docker参数如图
![image](https://github.com/HalcyonAzure/lsky-pro-docker/assets/117721493/fd259cda-3253-4eca-a6be-d0a50bb19a25)

2.在终端执行了相关以下指令
docker exec -it lskypro sed -i '32 a \\\Illuminate\\Support\\Facades\\URL::forceScheme('"'"'https'"'"');' /var/www/html/app/Providers/AppServiceProvider.php

配置完成后内网访问页面无法正常加载，具体显示如下：
![image](https://github.com/HalcyonAzure/lsky-pro-docker/assets/117721493/38364d9f-7f49-4b25-9f00-4ca904f547de)

**Comment by 99Mr-Z** [comment]
重新配置且不执行这条指令：
docker exec -it lskypro sed -i '32 a \\Illuminate\Support\Facades\URL::forceScheme('"'"'https'"'"');' /var/www/html/app/Providers/AppServiceProvider.php
是能够正常访问的

**Comment by HalcyonAzure** [comment]
HTTPS的访问问题在 #39 中应该已经得到了解决，目前应该不需要执行该指令了，稍后就在README那边做个更新🙏

**Comment by HalcyonAzure** [comment]
这边没问题我先把这个issue给close了，后续如果还有问题可以再re-open

**Comment by 99Mr-Z** [comment]
> 这边没问题我先把这个issue给close了，后续如果还有问题可以再re-open

不好意思，没有及时关闭这个ISSUE，已经通过其他方式解决了反代，谢谢

**Comment by stkroot** [comment]
> > 这边没问题我先把这个issue给close了，后续如果还有问题可以再re-open
> 
> 不好意思，没有及时关闭这个ISSUE，已经通过其他方式解决了反代，谢谢


你怎么解决的？我用反代后，也出现页面加载不全问题

**Comment by 99Mr-Z** [comment]
> > > 这边没问题我先把这个issue给close了，后续如果还有问题可以再re-open
> > 
> > 
> > 不好意思，没有及时关闭这个ISSUE，已经通过其他方式解决了反代，谢谢
> 
> 你怎么解决的？我用反代后，也出现页面加载不全问题

1.ASSET_URL的变量值需要填写外网访问地址
2.反向代理配置的参数
3.调整使用HTTPS的访问

**Comment by 99Mr-Z** [comment]
> > > 这边没问题我先把这个issue给close了，后续如果还有问题可以再re-open
> > 
> > 
> > 不好意思，没有及时关闭这个ISSUE，已经通过其他方式解决了反代，谢谢
> 
> 你怎么解决的？我用反代后，也出现页面加载不全问题

具体可以参考这篇教程
https://www.jackiewu.top/article/lskypro-picgo-installation#54161905e0414985893534d28e6db5ef
