### ISSUE TITLE
Arm 版使用最新版无法启动

### ISSUE THREAD

**Issue by Zeta-ZhaoLi** [HalcyonAzure/lsky-pro-docker#44]
之前是可以的，现在报错：
`exec /entrypoint.sh: exec format error`

**Comment by HalcyonAzure** [comment]
使用的是目前最新的镜像吗？昨晚的时候应该有一轮镜像的手动更新。咱身边暂时没有arm的设备，得晚点回去才能看看咋回事了😢

**Comment by Zeta-ZhaoLi** [comment]
> 使用的是目前最新的镜像吗？昨晚的时候应该有一轮镜像的手动更新。咱身边暂时没有arm的设备，得晚点回去才能看看咋回事了😢

刚刚重建了一个，又运行成功了，可能自动更新的时候出了什么问题吧

**Comment by HalcyonAzure** [comment]
解决问题就好👍，那我先close
了。后续如果出现了问题可以再reopen~
