### ISSUE TITLE
数据库容器对应IP变动（watchtower自动更新所致），修改.env手动重连

### ISSUE THREAD

**Issue by zhouxvmiao** [HalcyonAzure/lsky-pro-docker#45]
登录结果报错`HTTP 500`
![image](https://github.com/HalcyonAzure/lsky-pro-docker/assets/18864320/2429265b-dd02-4ff3-a0f5-72ccad9585df)
根据反复构建容器的结果来看，我应该需要修改持久卷中某个文件的参数，希望能得到您的提示！

**Comment by zhouxvmiao** [comment]
停机时间大概为5月7日晚上11点左右

**Comment by HalcyonAzure** [comment]
数据库使用的是mysql吗？看起来是lsky的容器和数据库之间的网络通信出现了问题。能贴一份不包含密码信息的compose文件看看吗?

**Comment by zhouxvmiao** [comment]
> 数据库使用的是mysql吗？看起来是lsky的容器和数据库之间的网络通信出现了问题。能贴一份不包含密码信息的compose文件看看吗?
的确是用的mysql，你的推测是正确的，根据我的检查，应该是5月7号晚上watchtower更新了mysql，导致容器IP发生了变化。请问我在lsky-pro中的哪个文件可以把mysql的地址修改正确？

**Comment by HalcyonAzure** [comment]
在docker容器挂载的lsky的目录`/var/www/html/`内会有一个`.env`文件，这个文件里面存储了和数据库连接相关的参数。你可以先试试看自己调整下能不能让网络连通，如果还有问题可以再留言

**Comment by zhouxvmiao** [comment]
非常感谢您的解答，问题通过修改.env文件中mysql的地址得以解决。
这也给其它人一个提醒，开启watchtower自动更新后，容器的IP可能会随着容器的更新而变化，在试图链接容器时要尽量使用172.17.0.1，而不是172.17.0.*。

**Comment by HalcyonAzure** [comment]
提问的内容里面包含了你的图床域名，我刚刚将对应的图片删除了，避免一些不必要的安全隐患（
