### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by cybaijie** [HalcyonAzure/lsky-pro-docker#46]
https://github.com/HalcyonAzure/lsky-pro-docker/issues/42 和他遇到的一样500 。。。

**Comment by cybaijie** [comment]
一开始能进入界面配置服MYSQL，等我配置完后就HTTP ERROR 500

**Comment by HalcyonAzure** [comment]
使用`sqlite`会出现一样的问题吗？

**Comment by cybaijie** [comment]
不会，使用sqlite正常，我也换了个MYSQL但还是一样，我现在就是用的sqlite

**Comment by HalcyonAzure** [comment]
我刚刚尝试拉取了最新的镜像（镜像的`id`是`73f1566f7839`），没能复现这个问题，使用`mysql`的话是可以正常安装的。如果对`mysql`不存在强需求也许就先用`sqlite`用着？如果对`mysql`有需求的话也可以研究看看是咋回事 :wink:

**Comment by cybaijie** [comment]
嗯嗯，能用就行了，不折腾了一开始我一直死磕mysql研究了一晚上，今早发现sqlite能用就不打算搞了
