### ISSUE TITLE
Docker启动时报AH00558、AH01909、AH00163、AH00094错误

### ISSUE THREAD

**Issue by tiansti** [HalcyonAzure/lsky-pro-docker#47]
![337480496-ded722a9-f1b4-4ecb-9e8c-07f25e32d5d9](https://github.com/HalcyonAzure/lsky-pro-docker/assets/109950792/2f44e1f8-dec2-456f-8e47-1f24cf34101e)

如上图所示，重新拉取了最新镜像也报错，用的群晖的docker

**Comment by HalcyonAzure** [comment]
这个应该只是Apache的警告，不影响使用才对。是遇到了什么问题吗？

**Comment by tiansti** [comment]
> 这个应该只是Apache的警告，不影响使用才对。是遇到了什么问题吗？

网页会显示无法访问，进入不到图床的页面

**Comment by tiansti** [comment]
> 这个应该只是Apache的警告，不影响使用才对。是遇到了什么问题吗？

应该是我的问题，我重新新建了一个容器可以正常启动

**Comment by HalcyonAzure** [comment]
ok，那我先把issue给close了~后面有问题再reopen就行
