### ISSUE TITLE
数据库未备份，如何手动恢复图片和URL映射

### ISSUE THREAD

**Issue by Solmonz** [HalcyonAzure/lsky-pro-docker#48]
大佬 请问下 docker 版本 配置的储存是webDav (alist  挂载网盘给sky 使用)  机器boon 了，现在重装完，要咋样才能把之前的图片链接起来 能正常使用

<img width="1104" alt="image" src="https://github.com/user-attachments/assets/0ea0079e-0963-4c95-8c59-8b086c8164a9">

**Comment by HalcyonAzure** [comment]
重装之前有备份lsky的数据库吗？lsky的图片和对应的url都是在数据库里面有映射的

**Comment by Solmonz** [comment]
机器boom了，啥也没了 （之前图片还在WebDAV 网盘里）

**Comment by HalcyonAzure** [comment]
> 机器boom了，啥也没了 （之前图片还在WebDAV 网盘里）

😢 那我猜测可能就要手动给数据库里面写图片和url的映射了，我这边没啥好的思路了。图片量很大吗？

**Comment by Solmonz** [comment]
应该不多吧，我就写博客的里面插图……

大佬咋映射

**Comment by HalcyonAzure** [comment]
数据库这边可以查到图片和链接关键字的信息：
![image](https://github.com/user-attachments/assets/179f0465-c506-4b62-bcc3-fdb3226c9cc8)
图片量不是很大的话可以试试看上传图片以后在数据库里面把'key'字段改成原来图片对应的url随机字段试试？

上面数据库对应的字段就是我下面这个图的，获取的url也是`https://domain.com/oHhxGK.png`这种格式，和数据库就对上了
![image](https://github.com/user-attachments/assets/cfedcc5e-8c45-4b70-b345-2aacf4285020)

**Comment by Solmonz** [comment]
我应该有几百张……

**Comment by HalcyonAzure** [comment]
> 我应该有几百张……

😢 那我认知里面应该就只能下次记得备份数据库了。。

**Comment by HalcyonAzure** [comment]
这边我就先把这个issue给关了，如果后面有更好的方法可以分享一下~

**Comment by Solmonz** [comment]
大佬 请问这个在哪查看 我看下我映射的路径下 没有这些内容
docker run -d \
    --name lsky-pro \
    --restart unless-stopped \
    -p 8089:8089 \
    -v $PWD/lsky:/var/www/html \
    -e WEB_PORT=8089 \
    halcyonazure/lsky-pro-docker:latest
    
    我不是对接的数据库 我是对接的webdav  alist 的webdav
<img width="962" alt="image" src="https://github.com/user-attachments/assets/c925e919-e19a-439c-99bf-44b6e4eb54d1">

**Comment by HalcyonAzure** [comment]
这块是Lsky的网页部分的内容，数据没有存放在这块。我自己没有用webdav来映射，但是我猜测如果映射的话，映射关系应该也是存放在数据库里面，而不是网页这边。

挂载目录的话，它应该就在你执行命令行的目录下。你可以试试看输入下面这个指令来查询路径👇
```shell
docker inspect lsky-pro | grep lsky:/var/www/html
```

**Comment by Solmonz** [comment]
<img width="974" alt="image" src="https://github.com/user-attachments/assets/efe4cae6-5906-4e28-8301-d1bffcfc91ee">
 就是我提供的这个目录 但是我没找到images 这个目录 或者文件
 
 那我要在那找到这个数据库文件 进行修改 或者修订

**Comment by HalcyonAzure** [comment]
我这边用本地存储的话，在`storage/app/uploads`路径下会有上传的图片路径，webdav的话我就不太清楚会不会有对应缓存了。

连接数据库的话，你是用`mysql`作为网页初始化的网站吗？还是`sqlite`这种本地文件呢

**Comment by Solmonz** [comment]
sqlite  大佬 我使用的 大佬有TG 吗 方便请教下您

**Comment by HalcyonAzure** [comment]
[HalcyonAzure](https://t.me/HalcyonAzure)
