### ISSUE TITLE
Docker运行500报错，但是图库里的图片访问正常

### ISSUE THREAD

**Issue by iNiL0119** [HalcyonAzure/lsky-pro-docker#49]
1个月之前通过docker安装了mysql，然后安装lsky pro，初始设置也都正常，页面可以正常打开。后来硬盘被我拿出来再放回去docker应用都没了，再次安装mysql和lsky pro，mysql正常后者不能打开页面显示500错误，但是之前上传的图片可以正常访问，就是控制台首页打不开。

docker日志：
![QG06 _MRKKMK@N1_3D1}AYN](https://github.com/user-attachments/assets/2a4f818f-4f4e-49be-954e-606082784815)

主页：
![BKMV`ZYMMNY{~T7(TFE 1VD](https://github.com/user-attachments/assets/48a94d88-846c-4676-bf9a-24a81d68f434)

图片正常显示：
![image](https://github.com/user-attachments/assets/8cc7f7ea-23b8-4d2c-b71b-282a60fb4818)

**Comment by HalcyonAzure** [comment]
部署的时候是全部依赖于群晖的图形化吗？500的话我自己来说是Lsky没有连上数据库，但是你这边图片又能查看就比较奇怪 🤔

**Comment by iNiL0119** [comment]
> 依赖于群晖的图形化吗？500的话我自己来说是Lsky没有连上数据库，但是你这边图片又能查看就比较奇

图形化操作，因为第一次安装都没问题，先mysql，然后lsky pro都没问题，第二次安装估计数据库数据还在磁盘上，只是软件被卸载了，所以可以直接访问原始图片。运行日志头几条我看了前面的人说过了，是关于Apache之类的，但是你说没影响，所以也不知道具体是什么问题。等过几天格式化了，重新试试。但这个问题只是我运气好，还是别人也遇到过就不知道了

**Comment by HalcyonAzure** [comment]
如果是图形化重新部署的话，在你lsky那边挂载的文件夹里面应该有一个.env的文件，可以试试看参考这个issue：[#45](https://github.com/HalcyonAzure/lsky-pro-docker/issues/45#issuecomment-2102325246)
